### ISSUE TITLE
Is monterey possible?

### ISSUE THREAD

**Issue by leonyaaaaaaa** [wildtigon/Hackintosh-Opencore-Asrock-B550M-Bigsur#2]
i'm thinking about settling up a hack on 3600x (asrock b550m pro4). Have you tried monterey on your build? does it work fine?

**Comment by wildtigon** [comment]
Hi @leonyaaaaaaa : I think this EFI won't work with Monterey. Moreover, I have switched to Mac Studio and sold Ryzentosh PC. So I can't keep support on it. Sorry for that
